export default [
    'Personal Details',
    'Visa Information', 
    'English Language Proficiency',
    'Education and Employment History',
    'Course Information',
    'Unique Student Identifier (USI)*',
    'Payment Options',
    'Terms and Conditions',
    'Declaration and Signature',
    'Representative Referral (OPTIONAL)',
    'Office Use Only',
    'Avetmiss Student Questionnaire',
    'Attachment Upload',
]